# Generated by Django 4.1.2 on 2022-11-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='platform',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
