# Generated by Django 4.1.2 on 2022-11-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_categories_options_alter_products_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='platform',
            field=models.CharField(choices=[('PS4', 'PS4'), ('PS5', 'PS5'), ('XBOX ONE', 'XBOX ONE'), ('XBOX SERIES X', 'XBOX SERIES X'), ('SWITCH', 'SWITCH')], max_length=254, null=True),
        ),
    ]
